#!/bin/sh
# Usage: execore-replay execore.tar.gz
set -e -u -x
diff=$(command -v colordiff || command -v diff) || {
    set +x
    echo >&2
    echo "Error: neither colordiff nor diff found in \$PATH" >&2
    echo >&2
    exit 1
}
basedir=$(cd "$(dirname "$0")" && pwd)
tgz=$1
execore=$(command -v execore) || {
    set +x
    echo >&2
    echo "Error: execore must be in \$PATH" >&2
    echo >&2
    exit 1
}
workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT
tar -C "$workdir" -xf "$tgz"
{
    trace0=$(find "$workdir" -name trace.0) && [ -n "$trace0" ]
} || {
    set +x
    echo >&2
    echo "Error: $tgz does not contain any traces" >&2
    echo >&2
    exit 1
}
pwd=$(pwd)
cd "$(dirname "$trace0")"
epoch=0
while [ -e trace."$epoch" ]; do
    max_insns=$(grep -c ^\\[ trace."$epoch")
    max_insns=$((max_insns - 1))
    "$execore" --sysroot="$workdir" core."$epoch" \
        --batch \
        --eval-command="source $basedir/execore-record.py" \
        --eval-command="execore-replay $max_insns $epoch"
    epoch=$((epoch + 1))
done
i=0
while [ "$i" -lt "$epoch" ]; do
    "$diff" --unified=50 trace."$i".r trace."$i" || true
    i=$((i + 1))
done >"$pwd"/execore.diff
set +x
if [ -s "$pwd"/execore.diff ]; then
    echo >&2
    echo "Traces do not match, check $pwd/execore.diff" >&2
    echo >&2
    exit 1
else
    echo >&2
    echo "Traces match" >&2
    echo >&2
fi
