on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

name: Continuous integration

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: sudo apt-get install -y black colordiff flake8 gdb shellcheck shfmt

    - name: Allow ssh localhost
      run: mkdir -m 700 -p ~/.ssh &&
           ssh-keygen -t ecdsa -f ~/.ssh/id_ecdsa -N "" &&
           cat ~/.ssh/id_ecdsa.pub >>~/.ssh/authorized_keys &&
           ssh -o StrictHostKeyChecking=no localhost true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
