on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

name: Continuous integration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: sudo apt-get update &&
           sudo apt-get install -y black colordiff flake8 gdb gcc-s390x-linux-gnu shellcheck shfmt

    - name: Allow ssh localhost
      run: mkdir -m 700 -p ~/.ssh &&
           ssh-keygen -t ecdsa -f ~/.ssh/id_ecdsa -N "" &&
           cat ~/.ssh/id_ecdsa.pub >>~/.ssh/authorized_keys &&
           ssh -o StrictHostKeyChecking=no localhost true

    - name: Configure CMake (Debug)
      run: cmake -B ${{github.workspace}}/cmake-build-debug -DCMAKE_BUILD_TYPE=Debug

    - name: Build (Debug)
      run: cmake --build ${{github.workspace}}/cmake-build-debug --config Debug

    # - name: Setup upterm session (Debug)
    #   uses: lhotari/action-upterm@v1

    - name: Test (Debug)
      working-directory: ${{github.workspace}}/cmake-build-debug
      run: ctest -C Debug --output-on-failure

    - name: Configure CMake (Release)
      run: cmake -B ${{github.workspace}}/cmake-build-release -DCMAKE_BUILD_TYPE=Release

    - name: Build (Release)
      run: cmake --build ${{github.workspace}}/cmake-build-release --config Release

    # - name: Setup upterm session (Release)
    #   uses: lhotari/action-upterm@v1

    - name: Test (Release)
      working-directory: ${{github.workspace}}/cmake-build-release
      run: ctest -C Release --output-on-failure

    - name: Configure CMake (s390x Debug)
      run: cmake -B ${{github.workspace}}/cmake-build-s390x-debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=s390x-linux-gnu-gcc

    - name: Build (s390x Debug)
      run: cmake --build ${{github.workspace}}/cmake-build-s390x-debug --config Debug

    - name: Configure CMake (s390x Release)
      run: cmake -B ${{github.workspace}}/cmake-build-s390x-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=s390x-linux-gnu-gcc

    - name: Build (s390x Release)
      run: cmake --build ${{github.workspace}}/cmake-build-s390x-release --config Release
